info:
  app:
    name: Customer Service

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: customer-service
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:33306/cs}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:cs}
    password: ${DATASOURCE_PASSWORD:cs}
    flyway:
      user: ${DATASOURCE_USERNAME:cs}
      password: ${DATASOURCE_PASSWORD:cs}

  cloud:
    stream:
      default:
        group: CustomerService
        producer:
          header-mode: none
      kafka:
        binder:
          brokers: ${KAFKA_BROKER_LIST:localhost:9092}
          configuration:
            security:
              protocol: PLAINTEXT
        bindings:
          default:
            consumer:
              ack-mode: record
        default:
          content-type: application/json
          consumer:
            start-offset: latest
      bindings:
        default:
          content-type: application/json
    function:
      definition:

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_HOST:localhost:8761}/eureka/