global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'infnet-ecommerce'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [
        'pfs:8080',
        'sfs:8080',
        'cs:8080',
        'host.docker.internal:8080',
        'host.docker.internal:8081',
        'host.docker.internal:8082',
        'host.docker.internal:8083',
      ]