global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'localhost:9090' ]
  - job_name: 'infnet-ecommerce'
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: [
        'product-feed-service:8080',
        'customer-service:8082',
        'storefront-service:8081',
        'order-processing-service:8084',
        'payment-service:8083',

        'host.docker.internal:8080',
        'host.docker.internal:8081',
        'host.docker.internal:8082',
        'host.docker.internal:8083',
        'host.docker.internal:8084',
        'host.docker.internal:9999',
        'host.docker.internal:8761',
      ]