info:
  app:
    name: Ecommerce Gateway

server:
  port: 9999

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}

spring:
  application:
    name: ecommerce-gateway
  cloud:
    gateway:
      routes:
        - id: storefront
          uri: lb://STOREFRONT-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/storefront-service/**
        - id: customer
          uri: lb://CUSTOMER-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/customer-service/**
        - id: payment
          uri: lb://PAYMENT-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/payment-service/**
        - id: order-processing
          uri: lb://ORDER-PROCESSING-SERVICE
          filters:
            - StripPrefix=1
          predicates:
            - Path=/order-processing-service/**

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
    healthcheck:
      enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /storefront-service/v3/api-docs
        name: Storefront Service
      - url: /customer-service/v3/api-docs
        name: Customer Service
      - url: /payment-service/v3/api-docs
        name: Payment Service
      - url: /order-processing-service/v3/api-docs
        name: Order Processing Service

loki:
  host: localhost
  port: 3100