info:
  app:
    name: Storefront Service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    tags:
      application: ${spring.application.name}

springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: storefront-service
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:23306/sfs}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:sfs}
    password: ${DATASOURCE_PASSWORD:sfs}
    flyway:
      user: ${DATASOURCE_USERNAME:sfs}
      password: ${DATASOURCE_PASSWORD:sfs}

  cloud:
    stream:
      default:
        group: StorefrontService
        producer:
          header-mode: none
      kafka:
        binder:
          brokers: ${KAFKA_BROKER_LIST:localhost:9092}
          configuration:
            security:
              protocol: PLAINTEXT
        bindings:
          default:
            consumer:
              ack-mode: record
        default:
          content-type: application/json
          consumer:
            start-offset: latest
      bindings:
        default:
          content-type: application/json
        #Producer kafka topic
        orderProducer-out-0:
          destination: Order
        #Consumer kafka topic
        productDataFeedConsumer-in-0:
          destination: ProductDataFeed
        orderProcessedConsumer-in-0:
          destination: OrderProcessed
    function:
      definition: productDataFeedConsumer;orderProcessedConsumer

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
  client:
    service-url:
      default-zone: http://${EUREKA_HOST:localhost:8761}/eureka/
    healthcheck:
      enabled: true

tasks:
  order-placement:
    cron-expression: "0 0/1 * * * *"

loki:
  host: localhost
  port: 3100