info:
  app:
    name: Storefront Service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info

springdoc:
  swagger-ui:
    path: /

spring:
  application:
    name: storefront-service
  jpa:
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:23306/sfs}
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DATASOURCE_USERNAME:sfs}
    password: ${DATASOURCE_PASSWORD:sfs}
    flyway:
      user: ${DATASOURCE_USERNAME:sfs}
      password: ${DATASOURCE_PASSWORD:sfs}

  cloud:
    stream:
      default:
        group: StorefrontService
        producer:
          header-mode: none
      kafka:
        binder:
          brokers: ${KAFKA_BROKER_LIST:localhost:9092}
          configuration:
            security:
              protocol: PLAINTEXT
        bindings:
          default:
            consumer:
              ack-mode: record
        default:
          content-type: application/json
          consumer:
            start-offset: latest
      bindings:
        default:
          content-type: application/json
        #Consumer kafka topic
        productDataFeedConsumer-in-0:
          destination: ProductDataFeed
    function:
      definition: productDataFeedConsumer

eureka:
  client:
    service-url:
      default-zone: http://${EUREKA_HOST:localhost:8761}/eureka/